#!/bin/bash

# Deployment Setup Script for engineeringwithsebs
# This script helps you set up environment variables for Vercel deployment

set -e

echo "======================================"
echo "  engineeringwithsebs - Deploy Setup  "
echo "======================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Generated token
REVALIDATE_TOKEN="ecc106c5c0764495a0fc47ac21ea4fc22003188661ec2a4660b318acadd3f787"

echo -e "${GREEN}✓${NC} Revalidation token generated:"
echo -e "${YELLOW}$REVALIDATE_TOKEN${NC}"
echo ""

# Get Vercel URL from user
echo "Enter your Vercel deployment URL:"
echo "  - If you haven't deployed yet, you can use a temporary URL"
echo "  - Format: https://engineeringwithsebs.vercel.app"
echo "  - Or custom domain: https://engineeringwithsebs.com"
read -p "Vercel URL: " VERCEL_URL

# Remove trailing slash if present
VERCEL_URL=${VERCEL_URL%/}

echo ""
echo -e "${GREEN}Step 1: Backend (Fly.io) Secrets${NC}"
echo "======================================"
echo ""
echo "Run these commands in your baas directory:"
echo ""
echo -e "${YELLOW}cd /Users/sebastiangil/workspace/baas${NC}"
echo ""
echo -e "${YELLOW}fly secrets set VERCEL_REVALIDATE_TOKEN=\"$REVALIDATE_TOKEN\"${NC}"
echo ""
echo -e "${YELLOW}fly secrets set VERCEL_REVALIDATE_URL=\"$VERCEL_URL/api/revalidate\"${NC}"
echo ""
echo -e "${YELLOW}fly secrets set CORS_ORIGINS=\"$VERCEL_URL\"${NC}"
echo ""
echo "If you have a custom domain with www, also add:"
echo -e "${YELLOW}fly secrets set CORS_ORIGINS=\"$VERCEL_URL,https://www.engineeringwithsebs.com\"${NC}"
echo ""
echo "To verify:"
echo -e "${YELLOW}fly secrets list${NC}"
echo ""
echo ""
echo -e "${GREEN}Step 2: Vercel Environment Variables${NC}"
echo "======================================"
echo ""
echo "Option A: Via Vercel Dashboard"
echo "-------------------------------"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Select your project (or import from GitHub: sebGilR/engineeringwithsebs)"
echo "3. Go to Settings → Environment Variables"
echo "4. Add these variables for Production, Preview, and Development:"
echo ""
echo "   BAAS_API_URL"
echo "   Value: https://baas-dry-sun-7571.fly.dev"
echo ""
echo "   NEXT_PUBLIC_SITE_URL"
echo "   Value: $VERCEL_URL"
echo ""
echo "   NEXT_PUBLIC_BLOG_SLUG"
echo "   Value: engineeringwithsebs"
echo ""
echo "   VERCEL_REVALIDATE_TOKEN"
echo "   Value: $REVALIDATE_TOKEN"
echo ""
echo ""
echo "Option B: Via Vercel CLI"
echo "------------------------"
echo "Run these commands:"
echo ""
echo -e "${YELLOW}vercel env add BAAS_API_URL production${NC}"
echo "  → https://baas-dry-sun-7571.fly.dev"
echo ""
echo -e "${YELLOW}vercel env add NEXT_PUBLIC_SITE_URL production${NC}"
echo "  → $VERCEL_URL"
echo ""
echo -e "${YELLOW}vercel env add NEXT_PUBLIC_BLOG_SLUG production${NC}"
echo "  → engineeringwithsebs"
echo ""
echo -e "${YELLOW}vercel env add VERCEL_REVALIDATE_TOKEN production${NC}"
echo "  → $REVALIDATE_TOKEN"
echo ""
echo ""
echo -e "${GREEN}Step 3: Deploy Updated Backend${NC}"
echo "======================================"
echo ""
echo "The fly.toml has been updated for production (always-on, 512MB RAM)."
echo "Deploy the updated configuration:"
echo ""
echo -e "${YELLOW}cd /Users/sebastiangil/workspace/baas${NC}"
echo -e "${YELLOW}fly deploy${NC}"
echo ""
echo ""
echo -e "${GREEN}Step 4: Deploy to Vercel${NC}"
echo "======================================"
echo ""
echo "Option A: Via Vercel Dashboard (Recommended)"
echo "--------------------------------------------"
echo "1. Go to: https://vercel.com/new"
echo "2. Import: sebGilR/engineeringwithsebs"
echo "3. Add environment variables (from Step 2)"
echo "4. Click Deploy"
echo ""
echo "Option B: Via Vercel CLI"
echo "------------------------"
echo -e "${YELLOW}vercel --prod${NC}"
echo ""
echo ""
echo -e "${GREEN}Step 5: Verify Deployment${NC}"
echo "======================================"
echo ""
echo "After deployment, test these:"
echo ""
echo "1. Homepage:"
echo "   $VERCEL_URL"
echo ""
echo "2. Login:"
echo "   $VERCEL_URL/login"
echo ""
echo "3. Dashboard:"
echo "   $VERCEL_URL/dashboard"
echo ""
echo "4. Sitemap:"
echo "   $VERCEL_URL/sitemap.xml"
echo ""
echo "5. RSS Feed:"
echo "   $VERCEL_URL/rss.xml"
echo ""
echo ""
echo -e "${GREEN}Environment Variables Summary${NC}"
echo "======================================"
echo ""
echo "VERCEL (Next.js):"
echo "  BAAS_API_URL: https://baas-dry-sun-7571.fly.dev"
echo "  NEXT_PUBLIC_SITE_URL: $VERCEL_URL"
echo "  NEXT_PUBLIC_BLOG_SLUG: engineeringwithsebs"
echo "  VERCEL_REVALIDATE_TOKEN: $REVALIDATE_TOKEN"
echo ""
echo "FLY.IO (Rails):"
echo "  VERCEL_REVALIDATE_TOKEN: $REVALIDATE_TOKEN"
echo "  VERCEL_REVALIDATE_URL: $VERCEL_URL/api/revalidate"
echo "  CORS_ORIGINS: $VERCEL_URL"
echo ""
echo ""
echo -e "${GREEN}✓ Setup complete!${NC}"
echo ""
echo "For detailed instructions, see:"
echo "  - QUICK_DEPLOY.md"
echo "  - DEPLOYMENT_CHECKLIST.md"
echo "  - VERCEL_DEPLOYMENT_GUIDE.md"
echo ""
